FROM golang:1.23-bullseye AS build-base

WORKDIR /app

COPY go.sum go.mod ./

RUN --mount=type=cache,target=/gp/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

FROM build-base AS dev

RUN go install github.com/air-verse/air@latest && \
    go install github.com/go-delve/delve/cmd/dlv@latest

COPY . .

CMD ["air", "-c", ".air.toml" ]

FROM build-base AS build-production

RUN useradd -u 1001 nonroot


COPY . .

RUN go build \
  -ldflags="-linkmode external -extldflags -static" \
  -tags netgo \
  -o healthcheck \
  ./healthcheck/healthcheck.go

RUN go build \
  -ldflags="-linkmode external -extldflags -static" \
  -tags netgo \
  -o api-golang

FROM scratch

ENV GIN_MODE=release

WORKDIR /

COPY --from=build-production /etc/passwd /etc/passwd

COPY --from=build-production /app/api-golang api-golang

USER NONROOT

EXPOSE 8080

CMD ["/api-golang"]








