name: image-ci

on:
  push:
    branches:
      - 'main'
    tags:
    - 'v*'

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            rhaisenberg/mydevopsdockercirepo
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./05-example-web-application/api-node/Dockerfile
          context: ./05-example-web-application/api-node/
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}

     # - name: Run Trivy vulnerability scanner
      #  uses: aquasecurity/trivy-action@master
       # with:
        #  image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
         # format: 'table'
          #exit-code: '1'
          #ignore-unfixed: true
          #vuln-type: 'os,library'
          #severity: 'CRITICAL'
